# This file defines variables containing lists of files. Because these lists
# are quite long we put them in a separate file to keep the other build files
# more tidy.

# List of public header files for the wxCharts library
set(PUBLIC_HEADER_DIR include/wx/charts)
set(wxcharts_HEADERS ${PUBLIC_HEADER_DIR}/wxareachart.h
                     ${PUBLIC_HEADER_DIR}/wxareachartctrl.h
                     ${PUBLIC_HEADER_DIR}/wxareachartdatasetoptions.h
                     ${PUBLIC_HEADER_DIR}/wxareachartoptions.h
                     ${PUBLIC_HEADER_DIR}/wxbarchart.h
                     ${PUBLIC_HEADER_DIR}/wxbarchartctrl.h
                     ${PUBLIC_HEADER_DIR}/wxbarchartdatasetoptions.h
                     ${PUBLIC_HEADER_DIR}/wxbarchartoptions.h
                     ${PUBLIC_HEADER_DIR}/wxboxplot.h
                     ${PUBLIC_HEADER_DIR}/wxboxplotctrl.h
                     ${PUBLIC_HEADER_DIR}/wxboxplotdatasetoptions.h
                     ${PUBLIC_HEADER_DIR}/wxboxplotoptions.h
                     ${PUBLIC_HEADER_DIR}/wxbubblechart.h
                     ${PUBLIC_HEADER_DIR}/wxbubblechartctrl.h
                     ${PUBLIC_HEADER_DIR}/wxbubblechartoptions.h
                     ${PUBLIC_HEADER_DIR}/wxcandlestickchart.h
                     ${PUBLIC_HEADER_DIR}/wxcandlestickchartctrl.h
                     ${PUBLIC_HEADER_DIR}/wxcandlestickchartoptions.h
                     ${PUBLIC_HEADER_DIR}/wxchart.h
                     ${PUBLIC_HEADER_DIR}/wxchartbackground.h
                     ${PUBLIC_HEADER_DIR}/wxchartbackgroundoptions.h
                     ${PUBLIC_HEADER_DIR}/wxchartcommonoptions.h
                     ${PUBLIC_HEADER_DIR}/wxchartctrl.h
                     ${PUBLIC_HEADER_DIR}/wxchartfontoptions.h
                     ${PUBLIC_HEADER_DIR}/wxchartmultitooltip.h
                     ${PUBLIC_HEADER_DIR}/wxchartmultitooltipoptions.h
                     ${PUBLIC_HEADER_DIR}/wxchartobservers.h
                     ${PUBLIC_HEADER_DIR}/wxchartoptions.h
                     ${PUBLIC_HEADER_DIR}/wxchartpadding.h
                     ${PUBLIC_HEADER_DIR}/wxcharts.h
                     ${PUBLIC_HEADER_DIR}/wxchartsarc.h
                     ${PUBLIC_HEADER_DIR}/wxchartsarcoptions.h
                     ${PUBLIC_HEADER_DIR}/wxchartsaxis.h
                     ${PUBLIC_HEADER_DIR}/wxchartsaxisoptions.h
                     ${PUBLIC_HEADER_DIR}/wxchartsbrushoptions.h
                     ${PUBLIC_HEADER_DIR}/wxchartscategoricalaxis.h
                     ${PUBLIC_HEADER_DIR}/wxchartscategoricaldata.h
                     ${PUBLIC_HEADER_DIR}/wxchartscategoricaldataobserver.h
                     ${PUBLIC_HEADER_DIR}/wxchartscircle.h
                     ${PUBLIC_HEADER_DIR}/wxchartscircleoptions.h
                     ${PUBLIC_HEADER_DIR}/wxchartsdataset.h
                     ${PUBLIC_HEADER_DIR}/wxchartsdatasetid.h
                     ${PUBLIC_HEADER_DIR}/wxchartsdatasettheme.h
                     ${PUBLIC_HEADER_DIR}/wxchartsdoubledataset.h
                     ${PUBLIC_HEADER_DIR}/wxchartselement.h
                     ${PUBLIC_HEADER_DIR}/wxchartsgrid.h
                     ${PUBLIC_HEADER_DIR}/wxchartsgridmapping.h
                     ${PUBLIC_HEADER_DIR}/wxchartsgridoptions.h
                     ${PUBLIC_HEADER_DIR}/wxchartslabel.h
                     ${PUBLIC_HEADER_DIR}/wxchartslabelgroup.h
                     ${PUBLIC_HEADER_DIR}/wxchartslabeloptions.h
                     ${PUBLIC_HEADER_DIR}/wxchartslegendctrl.h
                     ${PUBLIC_HEADER_DIR}/wxchartslegenditem.h
                     ${PUBLIC_HEADER_DIR}/wxchartslegendline.h
                     ${PUBLIC_HEADER_DIR}/wxchartslegendlineoptions.h
                     ${PUBLIC_HEADER_DIR}/wxchartslegendoptions.h
                     ${PUBLIC_HEADER_DIR}/wxchartslicedata.h
                     ${PUBLIC_HEADER_DIR}/wxchartsnumericalaxis.h
                     ${PUBLIC_HEADER_DIR}/wxchartsohlcdata.h
                     ${PUBLIC_HEADER_DIR}/wxchartspenoptions.h
                     ${PUBLIC_HEADER_DIR}/wxchartspoint.h
                     ${PUBLIC_HEADER_DIR}/wxchartspointoptions.h
                     ${PUBLIC_HEADER_DIR}/wxchartsprecisiontheme.h
                     ${PUBLIC_HEADER_DIR}/wxchartspresentationtheme.h
                     ${PUBLIC_HEADER_DIR}/wxchartsradialgrid.h
                     ${PUBLIC_HEADER_DIR}/wxchartsradialgridoptions.h
                     ${PUBLIC_HEADER_DIR}/wxchartsrectangle.h
                     ${PUBLIC_HEADER_DIR}/wxchartsrectangleoptions.h
                     ${PUBLIC_HEADER_DIR}/wxchartstheme.h
                     ${PUBLIC_HEADER_DIR}/wxchartsthemefactory.h
                     ${PUBLIC_HEADER_DIR}/wxchartsthemeid.h
                     ${PUBLIC_HEADER_DIR}/wxchartstimeaxis.h
                     ${PUBLIC_HEADER_DIR}/wxchartsutilities.h
                     ${PUBLIC_HEADER_DIR}/wxcharttooltip.h
                     ${PUBLIC_HEADER_DIR}/wxcharttooltipoptions.h
                     ${PUBLIC_HEADER_DIR}/wxcharttooltipprovider.h
                     ${PUBLIC_HEADER_DIR}/wxcolumnchart.h
                     ${PUBLIC_HEADER_DIR}/wxcolumnchartctrl.h
                     ${PUBLIC_HEADER_DIR}/wxcolumnchartdatasetoptions.h
                     ${PUBLIC_HEADER_DIR}/wxcolumnchartoptions.h
                     ${PUBLIC_HEADER_DIR}/wxcombinationchart.h
                     ${PUBLIC_HEADER_DIR}/wxcombinationchartctrl.h
                     ${PUBLIC_HEADER_DIR}/wxcombinationchartoptions.h
                     ${PUBLIC_HEADER_DIR}/wxdoughnutandpiechartbase.h
                     ${PUBLIC_HEADER_DIR}/wxdoughnutandpiechartoptionsbase.h
                     ${PUBLIC_HEADER_DIR}/wxdoughnutchart.h
                     ${PUBLIC_HEADER_DIR}/wxdoughnutchartctrl.h
                     ${PUBLIC_HEADER_DIR}/wxdoughnutchartoptions.h
                     ${PUBLIC_HEADER_DIR}/wxhistogram.h
                     ${PUBLIC_HEADER_DIR}/wxhistogramctrl.h
                     ${PUBLIC_HEADER_DIR}/wxhistogramoptions.h
                     ${PUBLIC_HEADER_DIR}/wxlinechart.h
                     ${PUBLIC_HEADER_DIR}/wxlinechartctrl.h
                     ${PUBLIC_HEADER_DIR}/wxlinechartdatasetoptions.h
                     ${PUBLIC_HEADER_DIR}/wxlinechartoptions.h
                     ${PUBLIC_HEADER_DIR}/wxmath2dplot.h
                     ${PUBLIC_HEADER_DIR}/wxmath2dplotctrl.h
                     ${PUBLIC_HEADER_DIR}/wxmath2dplotoptions.h
                     ${PUBLIC_HEADER_DIR}/wxohlcchart.h
                     ${PUBLIC_HEADER_DIR}/wxohlcchartctrl.h
                     ${PUBLIC_HEADER_DIR}/wxohlcchartoptions.h
                     ${PUBLIC_HEADER_DIR}/wxpiechart.h
                     ${PUBLIC_HEADER_DIR}/wxpiechartctrl.h
                     ${PUBLIC_HEADER_DIR}/wxpiechartoptions.h
                     ${PUBLIC_HEADER_DIR}/wxpolarareachart.h
                     ${PUBLIC_HEADER_DIR}/wxpolarareachartctrl.h
                     ${PUBLIC_HEADER_DIR}/wxpolarareachartoptions.h
                     ${PUBLIC_HEADER_DIR}/wxradarchart.h
                     ${PUBLIC_HEADER_DIR}/wxradarchartctrl.h
                     ${PUBLIC_HEADER_DIR}/wxradarchartoptions.h
                     ${PUBLIC_HEADER_DIR}/wxscatterplot.h
                     ${PUBLIC_HEADER_DIR}/wxscatterplotctrl.h
                     ${PUBLIC_HEADER_DIR}/wxscatterplotoptions.h
                     ${PUBLIC_HEADER_DIR}/wxstackedbarchart.h
                     ${PUBLIC_HEADER_DIR}/wxstackedbarchartctrl.h
                     ${PUBLIC_HEADER_DIR}/wxstackedbarchartdatasetoptions.h
                     ${PUBLIC_HEADER_DIR}/wxstackedbarchartoptions.h
                     ${PUBLIC_HEADER_DIR}/wxstackedcolumnchart.h
                     ${PUBLIC_HEADER_DIR}/wxstackedcolumnchartctrl.h
                     ${PUBLIC_HEADER_DIR}/wxstackedcolumnchartdatasetoptions.h
                     ${PUBLIC_HEADER_DIR}/wxstackedcolumnchartoptions.h
                     ${PUBLIC_HEADER_DIR}/wxtimeserieschart.h
                     ${PUBLIC_HEADER_DIR}/wxtimeserieschartctrl.h
                     ${PUBLIC_HEADER_DIR}/wxtimeserieschartoptions.h)
